name: Pull Request Checks

on:
  pull_request:
    branches: [ main ]

jobs:
  pr-review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check PR title
        uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          types: |
            fix
            feat
            chore
            docs
            style
            refactor
            deps
            test

      - name: Label PRs
        uses: actions/labeler@v4
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          configuration-path: .github/labeler.yml

  validate-commits:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check commit messages
        uses: wagoid/commitlint-github-action@v5

      - name: Check branch is up to date
        run: |
          git fetch origin main
          git merge-base --is-ancestor origin/main HEAD || (echo "Branch is not up to date with main. Please merge main into your branch." && exit 1)
